service: ex-invoicer-services
frameworkVersion: '3'

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs20.x
  timeout: 120

functions:
  main:
    handler: build/index.handler
    events:
      - http:
          method: any
          path: /{proxy+}
    environment:
      MONGO_URL: <..MONGO DATABASE CONNECTION STRING..>